//! E1 harness tests for the ELK port (docs/elk-port-plan.md).
//!
//! The oracle golden (`tools/elk-oracle/golden/*.stages.json`) is
//! generated by draw-uml + elkjs (see tools/elk-oracle/reference.mts)
//! and checked in, so these tests run offline. Regenerate with:
//!
//! ```sh
//! cd tools/elk-oracle && NODE_OPTIONS="--conditions=browser" \
//!   npx tsx reference.mts <fixture.puml> golden/<name>.stages.json
//! ```

use serde_json::Value;
use typstuml::layout::elk::compare::{coord_diff, json_semantic_diff};
use typstuml::layout::elk::graph::ElkNode;

fn stages() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/01-architecture.stages.json"
    );
    let data = std::fs::read_to_string(path).expect("oracle golden missing — see file header");
    serde_json::from_str(&data).expect("oracle golden is not valid JSON")
}

/// The ElkNode model must preserve every stage of the oracle dump
/// through a deserialize→serialize roundtrip: if elkjs emits a field
/// the model doesn't know, the `extra` flatten map must carry it. Any
/// diff here means the model would silently drop schema the port
/// needs.
#[test]
fn elk_graph_model_roundtrips_oracle_stages() {
    let stages = stages();
    for stage in ["pass1Input", "pass1Output", "pass2Input", "pass2Output"] {
        let original = stages.get(stage).unwrap_or_else(|| panic!("golden lacks stage {stage}"));
        let node: ElkNode = serde_json::from_value(original.clone())
            .unwrap_or_else(|e| panic!("{stage}: model cannot parse oracle output: {e}"));
        let round = serde_json::to_value(&node).unwrap();
        let diffs = json_semantic_diff(original, &round, 0.0);
        assert!(
            diffs.is_empty(),
            "{stage}: model roundtrip lost/changed {} field(s), first: {:?}",
            diffs.len(),
            diffs.first()
        );
    }
}

/// Benchmark sanity: the oracle layout must contain the structures the
/// port milestones key on (hierarchy, cross-hierarchy edges, routed
/// sections) so a regenerated golden that silently lost them fails
/// loudly here instead of green-lighting a vacuous comparison.
#[test]
fn oracle_golden_has_expected_shape() {
    let stages = stages();
    let output: ElkNode = serde_json::from_value(stages["pass2Output"].clone()).unwrap();

    let mut nodes = 0usize;
    let mut groups = 0usize;
    let mut edges = 0usize;
    output.walk(&mut |n| {
        nodes += 1;
        if n.children.as_ref().is_some_and(|c| !c.is_empty()) && n.id != output.id {
            groups += 1;
        }
        edges += n.edges.as_ref().map_or(0, |e| e.len());
    });
    // 01-architecture: 16 components + interface + 2 databases = 19
    // leaves (the title is added by post-processing, not ELK), plus 5
    // packages and the root: 25 nodes, 20 edges.
    assert_eq!(nodes, 25, "expected the full benchmark node tree");
    assert_eq!(groups, 5, "benchmark has 5 packages");
    assert_eq!(edges, 20, "benchmark has 20 edges");

    // Every leaf the layout ran on must have resolved coordinates.
    output.walk(&mut |n| {
        if n.id != output.id {
            assert!(n.x.is_some() && n.y.is_some(), "node {} lacks coordinates", n.id);
        }
    });

    // Edges must carry routed orthogonal sections.
    let mut routed = 0usize;
    output.walk(&mut |n| {
        if let Some(es) = &n.edges {
            routed += es.iter().filter(|e| e.sections.as_ref().is_some_and(|s| !s.is_empty())).count();
        }
    });
    assert_eq!(routed, 20, "all 20 edges must have routed sections");
}

/// E2 (importer): importing the benchmark's pass-2 input must produce
/// the exact LGraph structure elkjs's importer builds — same graph
/// nesting, same per-graph node/edge partition, one fresh anonymous
/// port per edge endpoint (mergeEdges=false), direction-derived port
/// sides, and Java's model-order quirks (nodes: decided by the direct
/// parent's options; edges: decided by the root's options at every
/// level).
#[test]
fn importer_builds_hierarchical_lgraph_matching_reference() {
    use typstuml::layout::elk::alg::graph::LGraphArena;
    use typstuml::layout::elk::alg::options::PortSide;
    use typstuml::layout::elk::alg::transform::import_graph;

    let stages = stages();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();

    let mut arena = LGraphArena::default();
    let top = import_graph(&mut arena, &input);

    let origin = |nid: &typstuml::layout::elk::alg::graph::LNodeId| {
        arena.nodes[nid.0].props.origin.clone().unwrap()
    };

    // Root graph: REST, M, RC + 5 groups, in document order.
    let root_nodes: Vec<String> =
        arena.graphs[top.0].layerless_nodes.iter().map(origin).collect();
    assert_eq!(
        root_nodes,
        ["REST", "M", "RC", "group_1", "group_2", "group_3", "group_4", "group_5"]
    );

    // Every group node owns a nested graph with the right children.
    let nested_of = |group: &str| -> Vec<String> {
        let gnode = arena
            .graphs[top.0]
            .layerless_nodes
            .iter()
            .find(|n| arena.nodes[n.0].props.origin.as_deref() == Some(group))
            .unwrap();
        let ng = arena.nodes[gnode.0].nested_graph.expect("group must have nested graph");
        arena.graphs[ng.0].layerless_nodes.iter().map(origin).collect()
    };
    assert_eq!(nested_of("group_1"), ["FE", "SV", "ED"]);
    assert_eq!(nested_of("group_2"), ["API"]);
    assert_eq!(nested_of("group_3"), ["GEN", "RES", "EDIT", "REG"]);
    assert_eq!(nested_of("group_4"), ["AST", "LAY", "TPL", "SCN", "RHTML", "RPPTX", "STO"]);
    assert_eq!(nested_of("group_5"), ["DAO"]);

    // Node model order: root children 0..8 in document order; nested
    // children get NONE (their parent groups don't set
    // considerModelOrder — Java decides by the direct parent).
    for (i, n) in arena.graphs[top.0].layerless_nodes.iter().enumerate() {
        assert_eq!(arena.nodes[n.0].props.model_order, Some(i as i32), "root child {i}");
    }
    assert_eq!(arena.graphs[top.0].props.max_model_order_nodes, 8);
    let fe = arena.nodes.iter().find(|n| n.props.origin.as_deref() == Some("FE")).unwrap();
    assert_eq!(fe.props.model_order, None);

    // Edges: 20 total, each with a model order (root strategy applies
    // at every level), each endpoint on a fresh port.
    assert_eq!(arena.edges.len(), 20);
    assert_eq!(arena.ports.len(), 40, "every edge endpoint gets its own anonymous port");
    let orders: Vec<i32> = arena.edges.iter().map(|e| e.props.model_order.unwrap()).collect();
    let mut sorted = orders.clone();
    sorted.sort_unstable();
    assert_eq!(sorted, (0..20).collect::<Vec<_>>());

    // Port sides under direction DOWN: source=SOUTH, target=NORTH.
    for e in &arena.edges {
        assert_eq!(arena.ports[e.source.unwrap().0].side, PortSide::South);
        assert_eq!(arena.ports[e.target.unwrap().0].side, PortSide::North);
    }

    // Padding parsed from "[top=50,left=30,bottom=30,right=30]" on
    // the groups; root has none in pass2Input (defaults to 12).
    let g1 = arena
        .graphs
        .iter()
        .find(|g| g.props.origin.as_deref() == Some("group_1"))
        .unwrap();
    assert_eq!(
        (g1.padding.top, g1.padding.left, g1.padding.bottom, g1.padding.right),
        (50.0, 30.0, 30.0, 30.0)
    );

    // Sizes copied verbatim.
    let api = arena.nodes.iter().find(|n| n.props.origin.as_deref() == Some("API")).unwrap();
    assert_eq!((api.size.x, api.size.y), (200.0, 63.0));
}

/// E2 (compound preprocessor): splitting the benchmark's 13
/// cross-hierarchy edges must produce exactly the segment structure
/// ELK builds — one external-port dummy per crossed boundary per edge
/// (mergeHierarchyEdges never kicks in because the importer gives
/// every edge endpoint its own anonymous port), a fresh port on each
/// crossed compound node, and 2 or 3 dummy-edge segments depending on
/// whether one endpoint sits at the root.
#[test]
fn compound_preprocessor_splits_cross_hierarchy_edges() {
    use typstuml::layout::elk::alg::compound::preprocess;
    use typstuml::layout::elk::alg::graph::{LGraphArena, NodeType};
    use typstuml::layout::elk::alg::options::{PortConstraints, PortSide, PortType};
    use typstuml::layout::elk::alg::transform::import_graph;

    let stages = stages();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();
    let mut arena = LGraphArena::default();
    let top = import_graph(&mut arena, &input);
    let edges_before = arena.edges.len();
    let ports_before = arena.ports.len();

    let cross_map = preprocess(&mut arena, top);

    // 13 root edges are cross-hierarchy; 7 intra-group edges are not.
    assert_eq!(cross_map.len(), 13);
    let mut seg_counts: Vec<usize> = cross_map.values().map(Vec::len).collect();
    seg_counts.sort_unstable();
    // group↔root edges (FE→REST, REST→API, RPPTX→RC, DAO→M): 2 segments;
    // group↔group edges (the other 9): 3 segments.
    assert_eq!(seg_counts, [2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3]);
    assert_eq!(arena.edges.len() - edges_before, 4 * 2 + 9 * 3, "35 dummy edges");

    // External-port dummies per nested graph: g1=2, g2=4, g3=8, g4=5,
    // g5=3 (one per crossing edge endpoint inside that group), and 22
    // matching fresh ports on the group nodes.
    let dummies: Vec<_> = arena
        .nodes
        .iter()
        .enumerate()
        .filter(|(_, n)| n.node_type == NodeType::ExternalPort)
        .collect();
    assert_eq!(dummies.len(), 22);
    assert_eq!(arena.ports.len() - ports_before, 22 + 22, "port per dummy + port per group");

    let group_dummy_count = |group: &str| -> usize {
        let g = arena
            .graphs
            .iter()
            .find(|g| g.props.origin.as_deref() == Some(group))
            .unwrap();
        g.layerless_nodes
            .iter()
            .filter(|n| arena.nodes[n.0].node_type == NodeType::ExternalPort)
            .count()
    };
    assert_eq!(group_dummy_count("group_1"), 2);
    assert_eq!(group_dummy_count("group_2"), 4);
    assert_eq!(group_dummy_count("group_3"), 8);
    assert_eq!(group_dummy_count("group_4"), 5);
    assert_eq!(group_dummy_count("group_5"), 3);

    // Every original cross-hierarchy edge is disconnected.
    for orig in cross_map.keys() {
        assert!(arena.edges[orig.0].source.is_none());
        assert!(arena.edges[orig.0].target.is_none());
    }

    // Group nodes got FIXED_SIDE constraints; their ports' sides match
    // the dummies' EXT_PORT_SIDE (direction DOWN: OUTPUT=South boundary
    // exit, INPUT=North boundary entry).
    for group in ["group_1", "group_2", "group_3", "group_4", "group_5"] {
        let gnode = arena
            .nodes
            .iter()
            .find(|n| n.props.origin.as_deref() == Some(group))
            .unwrap();
        assert_eq!(gnode.props.port_constraints, PortConstraints::FixedSide);
        for &p in &gnode.ports {
            assert!(matches!(arena.ports[p.0].side, PortSide::North | PortSide::South));
            assert!(arena.ports[p.0].props.port_dummy.is_some());
        }
    }

    // Spot-check one 3-segment edge: REST→API is 2 segments — inside
    // group_2 (INPUT) then at root — and the root segment starts at
    // REST's own port.
    let rest_api = cross_map
        .iter()
        .find(|(e, _)| arena.edges[e.0].props.origin.as_deref() == Some("e4"))
        .map(|(_, segs)| segs)
        .unwrap();
    assert_eq!(rest_api.len(), 2);
    assert_eq!(rest_api[0].port_type, PortType::Input);
    let root_seg = &rest_api[1];
    assert_eq!(root_seg.graph, top);
    let seg_source = arena.edge_source_node(root_seg.edge).unwrap();
    assert_eq!(arena.nodes[seg_source.0].props.origin.as_deref(), Some("REST"));
}

/// E3 (greedy cycle breaker): run phase 1 on every graph of the
/// nesting tree (bottom-up, fresh `Random(1)` per graph, exactly like
/// `ElkLayered.hierarchicalLayout` + `GraphConfigurator`). The
/// benchmark's only cycle lives at the root — group_1 → REST → group_2
/// → group_3 → group_4 → group_1 — and elkjs resolves it by reversing
/// the REST→API segment (visible in pass2Output as the one upward
/// edge). The port must reverse exactly that edge and nothing else.
#[test]
fn greedy_cycle_breaker_reverses_rest_to_api_segment() {
    use typstuml::layout::elk::alg::compound::preprocess;
    use typstuml::layout::elk::alg::graph::{LGraphArena, LGraphId};
    use typstuml::layout::elk::alg::p1_cycles::break_cycles;
    use typstuml::layout::elk::alg::random::JavaRandom;
    use typstuml::layout::elk::alg::transform::import_graph;

    let stages = stages();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();
    let mut arena = LGraphArena::default();
    let top = import_graph(&mut arena, &input);
    let cross_map = preprocess(&mut arena, top);

    // collectAllGraphsBottomUp: stack-collected, so children end up
    // before the root, in reverse discovery order.
    let mut graphs: Vec<LGraphId> = Vec::new();
    let mut discover = vec![top];
    while let Some(g) = discover.pop() {
        graphs.insert(0, g);
        for &n in &arena.graphs[g.0].layerless_nodes {
            if let Some(ng) = arena.nodes[n.0].nested_graph {
                discover.push(ng);
            }
        }
    }
    assert_eq!(graphs.len(), 6);
    assert_eq!(*graphs.last().unwrap(), top, "root processed last");

    let mut all_reversed = Vec::new();
    for g in graphs {
        let mut random = JavaRandom::new(1);
        all_reversed.extend(break_cycles(&mut arena, g, &mut random));
    }

    // Exactly one reversal in the whole hierarchy…
    assert_eq!(all_reversed.len(), 1, "only the root cycle needs breaking");
    let reversed = all_reversed[0];
    assert!(arena.edges[reversed.0].props.reversed);

    // …and it is the root segment of e4 (REST→API): after reversal it
    // runs group_2 → REST.
    let e4_segments = cross_map
        .iter()
        .find(|(e, _)| arena.edges[e.0].props.origin.as_deref() == Some("e4"))
        .map(|(_, segs)| segs)
        .unwrap();
    assert!(e4_segments.iter().any(|s| s.edge == reversed), "reversed edge must be e4's segment");
    let src = arena.edge_source_node(reversed).unwrap();
    let tgt = arena.edge_target_node(reversed).unwrap();
    assert_eq!(arena.nodes[src.0].props.origin.as_deref(), Some("group_2"));
    assert_eq!(arena.nodes[tgt.0].props.origin.as_deref(), Some("REST"));
}

/// Shared pipeline prefix for the layering tests: import → compound
/// preprocess → per-graph cycle breaking (bottom-up, Random(1) each)
/// → per-graph network-simplex layering → high-degree treatment where
/// the graph's own options enable it (only the root in the benchmark:
/// draw-uml sets highDegreeNodes on the root graph only).
/// Full flat crossing-minimization pipeline: layering, then the
/// before-phase-3 intermediate processors and the layer sweep, threading
/// one `JavaRandom` from the cycle breaker into the crossing minimizer
/// exactly as ELK's shared `InternalProperties.RANDOM` does. Flat graphs
/// only (single component in scope).
fn run_through_crossing_min(
    input: &ElkNode,
) -> (
    typstuml::layout::elk::alg::graph::LGraphArena,
    typstuml::layout::elk::alg::graph::LGraphId,
) {
    use typstuml::layout::elk::alg::graph::LGraphArena;
    use typstuml::layout::elk::alg::random::JavaRandom;
    use typstuml::layout::elk::alg::{components, intermediate, p1_cycles, p2_layers, preserve_order};
    use typstuml::layout::elk::alg::p3order::layer_sweep;

    let mut arena = LGraphArena::default();
    let top = typstuml::layout::elk::alg::transform::import_graph(&mut arena, input);

    for comp in components::split(&mut arena, top) {
        let mut random = JavaRandom::new(1);
        p1_cycles::break_cycles(&mut arena, comp, &mut random);
        p2_layers::layer_nodes(&mut arena, comp);
        if arena.graphs[comp.0].props.high_degree_nodes_treatment {
            typstuml::layout::elk::alg::high_degree::process(&mut arena, comp);
        }
        // before-phase-3 intermediate processors
        intermediate::long_edge_splitter(&mut arena, comp);
        intermediate::port_side_processor(&mut arena, comp);
        intermediate::inverted_port_processor(&mut arena, comp);
        intermediate::port_list_sorter(&mut arena, comp);
        preserve_order::sort_by_input_model(&mut arena, comp);
        // phase 3
        layer_sweep::layer_sweep_crossing_minimizer(&mut arena, comp, &mut random, &mut std::collections::HashMap::new());
    }
    (arena, top)
}

fn run_through_layering(
    input: &ElkNode,
) -> (
    typstuml::layout::elk::alg::graph::LGraphArena,
    typstuml::layout::elk::alg::graph::LGraphId,
) {
    use typstuml::layout::elk::alg::graph::{LGraphArena, LGraphId};
    use typstuml::layout::elk::alg::random::JavaRandom;

    let mut arena = LGraphArena::default();
    let top = typstuml::layout::elk::alg::transform::import_graph(&mut arena, input);
    typstuml::layout::elk::alg::compound::preprocess(&mut arena, top);

    let mut graphs: Vec<LGraphId> = Vec::new();
    let mut discover = vec![top];
    while let Some(g) = discover.pop() {
        graphs.insert(0, g);
        for &n in &arena.graphs[g.0].layerless_nodes {
            if let Some(ng) = arena.nodes[n.0].nested_graph {
                discover.push(ng);
            }
        }
    }
    // ELK runs ComponentsProcessor.split only on the flat layout path
    // (doLayout); the hierarchical path (doCompoundLayout) skips it. The
    // greedy cycle breaker consumes the resulting DFS node order, so the
    // gate matters for which edges get reversed.
    use typstuml::layout::elk::alg::options::HierarchyHandling;
    let is_compound = arena.graphs[top.0].props.hierarchy_handling
        == HierarchyHandling::IncludeChildren;

    for g in graphs {
        let comps = if is_compound {
            vec![g]
        } else {
            typstuml::layout::elk::alg::components::split(&mut arena, g)
        };
        for comp in comps {
            let mut random = JavaRandom::new(1);
            typstuml::layout::elk::alg::p1_cycles::break_cycles(&mut arena, comp, &mut random);
            typstuml::layout::elk::alg::p2_layers::layer_nodes(&mut arena, comp);
            if arena.graphs[comp.0].props.high_degree_nodes_treatment {
                typstuml::layout::elk::alg::high_degree::process(&mut arena, comp);
            }
        }
    }
    (arena, top)
}

/// Layer assignment of a graph as origin-id lists, one per layer.
fn layers_by_origin(
    arena: &typstuml::layout::elk::alg::graph::LGraphArena,
    g: typstuml::layout::elk::alg::graph::LGraphId,
) -> Vec<Vec<String>> {
    arena.graphs[g.0]
        .layers
        .iter()
        .map(|l| {
            l.nodes
                .iter()
                .map(|n| {
                    arena.nodes[n.0]
                        .props
                        .origin
                        .clone()
                        .unwrap_or_else(|| "<dummy>".to_string())
                })
                .collect()
        })
        .collect()
}

/// E4a (flat): the exact root-equivalent graph in
/// `tools/elk-oracle/golden/root-flat.input.json` was run through
/// elkjs (`root-flat.output.json`); its y-bands give the layer order
/// g2 | g3 | g5 | M | g4 | {RC, g1} | REST — network simplex layering
/// (5 layers) plus the high-degree treatment pulling the g5→M tree
/// out of g3 (degree 8 ≥ threshold 8) into two fresh layers.
#[test]
fn network_simplex_plus_high_degree_matches_flat_oracle() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/root-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (arena, top) = run_through_layering(&input);

    let mut layers = layers_by_origin(&arena, top);
    for l in layers.iter_mut() {
        l.sort();
    }
    assert_eq!(
        layers,
        vec![
            vec!["g2"],
            vec!["g3"],
            vec!["g5"],
            vec!["M"],
            vec!["g4"],
            vec!["RC", "g1"],
            vec!["REST"],
        ]
    );
}

/// E4b (hierarchical): the same layering must come out of the full
/// benchmark pipeline for the root graph, and the nested graphs must
/// layer their content + external-port dummies as hand-derived from
/// the segment structure (external dummies with North side feed the
/// first layer, South dummies trail).
#[test]
fn hierarchical_layering_matches_reference_structure() {
    let stages = stages();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();
    let (arena, top) = run_through_layering(&input);

    let mut root_layers = layers_by_origin(&arena, top);
    for l in root_layers.iter_mut() {
        l.sort();
    }
    assert_eq!(
        root_layers,
        vec![
            vec!["group_2"],
            vec!["group_3"],
            vec!["group_5"],
            vec!["M"],
            vec!["group_4"],
            vec!["RC", "group_1"],
            vec!["REST"],
        ]
    );

    // Nested graphs: group_2 = in-dummy | API | three out-dummies.
    let nested = |group: &str| {
        let gnode = arena
            .nodes
            .iter()
            .find(|n| n.props.origin.as_deref() == Some(group))
            .unwrap();
        gnode.nested_graph.unwrap()
    };
    let g2 = layers_by_origin(&arena, nested("group_2"));
    assert_eq!(
        g2,
        vec![
            vec!["<dummy>"],
            vec!["API"],
            vec!["<dummy>", "<dummy>", "<dummy>"],
        ]
    );

    // group_1: FE + the SCN..>SV entry dummy on top, SV + the FE→REST
    // exit dummy in the middle, ED last.
    let g1 = layers_by_origin(&arena, nested("group_1"));
    assert_eq!(g1.len(), 3);
    assert!(g1[0].contains(&"FE".to_string()) && g1[0].len() == 2);
    assert!(g1[1].contains(&"SV".to_string()) && g1[1].len() == 2);
    assert_eq!(g1[2], vec!["ED"]);

    // group_4: three entry dummies | AST LAY TPL | SCN | RHTML RPPTX
    // (+ SV exit dummy) | STO (+ RC exit dummy).
    let g4 = layers_by_origin(&arena, nested("group_4"));
    assert_eq!(g4.len(), 5, "library graph must span 5 layers, got {g4:?}");
    assert_eq!(g4[0], vec!["<dummy>", "<dummy>", "<dummy>"]);
    {
        let mut l1 = g4[1].clone();
        l1.sort();
        assert_eq!(l1, vec!["AST", "LAY", "TPL"]);
    }
    assert!(g4[2].contains(&"SCN".to_string()));
}

/// E5 stage A: after `LongEdgeSplitter` the layering must be *proper*
/// — every edge connects nodes in adjacent layers — and the number of
/// `LONG_EDGE` dummies must equal the total layer span the original
/// edges have to cross, i.e. Σ(|layer(t) − layer(s)| − 1). Node layers
/// already match the oracle (E4), so this pins the splitter exactly.
#[test]
fn long_edge_splitter_makes_layering_proper() {
    use typstuml::layout::elk::alg::graph::NodeType;

    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (mut arena, top) = run_through_layering(&input);

    // Expected dummy count from the (real-node) edge spans before split.
    let mut expected_dummies = 0usize;
    for e in 0..arena.edges.len() {
        let eid = typstuml::layout::elk::alg::graph::LEdgeId(e);
        let (Some(s), Some(t)) =
            (arena.edge_source_node(eid), arena.edge_target_node(eid))
        else {
            continue;
        };
        if arena.nodes[s.0].graph != top || arena.nodes[t.0].graph != top {
            continue;
        }
        let (ls, lt) = (arena.nodes[s.0].layer.unwrap(), arena.nodes[t.0].layer.unwrap());
        expected_dummies += ls.abs_diff(lt).saturating_sub(1);
    }

    typstuml::layout::elk::alg::intermediate::long_edge_splitter(&mut arena, top);

    // Postcondition 1: proper layering — every edge spans one layer.
    for e in 0..arena.edges.len() {
        let eid = typstuml::layout::elk::alg::graph::LEdgeId(e);
        let (Some(s), Some(t)) =
            (arena.edge_source_node(eid), arena.edge_target_node(eid))
        else {
            continue;
        };
        if arena.nodes[s.0].graph != top {
            continue;
        }
        let (ls, lt) = (arena.nodes[s.0].layer.unwrap(), arena.nodes[t.0].layer.unwrap());
        assert_eq!(ls.abs_diff(lt), 1, "edge {e} spans {ls}->{lt}, not adjacent");
    }

    // Postcondition 2: exactly the expected number of LONG_EDGE dummies.
    let dummies = arena
        .graphs[top.0]
        .layers
        .iter()
        .flat_map(|l| l.nodes.iter())
        .filter(|&&n| arena.nodes[n.0].node_type == NodeType::LongEdge)
        .count();
    assert_eq!(dummies, expected_dummies, "unexpected long-edge dummy count");
    assert!(expected_dummies > 0, "stress-flat should have long edges to split");
}

/// E5 stage B: after `PortSideProcessor` + `PortListSorter` every port
/// of a flat graph has a definite side (WEST inputs / EAST outputs — the
/// algorithm's normalized rightward orientation), real nodes are
/// FIXED_SIDE, and each node's ports are grouped by side (EAST before
/// WEST, ordinal-ascending). Structural, since the oracle only exposes
/// the post-sweep order.
#[test]
fn port_side_and_list_processing_assign_sides() {
    use typstuml::layout::elk::alg::graph::NodeType;
    use typstuml::layout::elk::alg::options::{PortConstraints, PortSide};

    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (mut arena, top) = run_through_layering(&input);
    typstuml::layout::elk::alg::intermediate::long_edge_splitter(&mut arena, top);
    typstuml::layout::elk::alg::intermediate::port_side_processor(&mut arena, top);
    typstuml::layout::elk::alg::intermediate::inverted_port_processor(&mut arena, top);
    typstuml::layout::elk::alg::intermediate::port_list_sorter(&mut arena, top);

    for layer in &arena.graphs[top.0].layers {
        for &n in &layer.nodes {
            let node = &arena.nodes[n.0];
            // Every port has a definite W/E side.
            let mut sides: Vec<i32> = Vec::new();
            for &p in &node.ports {
                let s = arena.ports[p.0].side;
                assert!(
                    s == PortSide::West || s == PortSide::East,
                    "port on node {n:?} has side {s:?}"
                );
                sides.push(s as i32);
            }
            // Ports grouped ascending by side ordinal (EAST=2 before WEST=4).
            assert!(sides.windows(2).all(|w| w[0] <= w[1]), "ports not side-grouped: {sides:?}");
            // Real nodes tightened to FIXED_SIDE; dummies stay FIXED_POS.
            if node.node_type == NodeType::Normal {
                assert_eq!(node.props.port_constraints, PortConstraints::FixedSide);
            } else if node.node_type == NodeType::LongEdge {
                assert_eq!(node.props.port_constraints, PortConstraints::FixedPos);
            }
        }
    }
}

/// E5: after the layer sweep, the within-layer order of the real nodes
/// must match elkjs. We compare the relative order of origin-bearing
/// nodes in each layer against the oracle's nodes in the same y-band,
/// ordered by x (DOWN direction ⇒ in-layer axis is x).
#[test]
fn crossing_min_matches_oracle_in_layer_order() {
    let read = |name: &str| {
        std::fs::read_to_string(format!(
            "{}/tools/elk-oracle/golden/{name}",
            env!("CARGO_MANIFEST_DIR")
        ))
        .unwrap()
    };
    let input: ElkNode = serde_json::from_str(&read("stress-flat.input.json")).unwrap();
    let output: ElkNode = serde_json::from_str(&read("stress-flat.output.json")).unwrap();

    // Oracle in-layer order per y-band.
    let mut ys: Vec<i64> = output
        .children
        .as_deref()
        .unwrap()
        .iter()
        .map(|c| c.y.unwrap().round() as i64)
        .collect();
    ys.sort_unstable();
    ys.dedup();
    let mut oracle: Vec<Vec<String>> = vec![Vec::new(); ys.len()];
    let mut by_band: std::collections::HashMap<usize, Vec<(f64, String)>> = Default::default();
    for c in output.children.as_deref().unwrap() {
        let band = ys.binary_search(&(c.y.unwrap().round() as i64)).unwrap();
        by_band.entry(band).or_default().push((c.x.unwrap(), c.id.clone()));
    }
    for (band, mut v) in by_band {
        v.sort_by(|a, b| a.0.total_cmp(&b.0));
        oracle[band] = v.into_iter().map(|(_, id)| id).collect();
    }

    let (arena, top) = run_through_crossing_min(&input);
    let mine: Vec<Vec<String>> = arena.graphs[top.0]
        .layers
        .iter()
        .map(|l| {
            l.nodes
                .iter()
                .filter_map(|n| arena.nodes[n.0].props.origin.clone())
                .collect()
        })
        .collect();

    assert_eq!(mine.len(), oracle.len(), "layer count");
    let mismatches: Vec<String> = mine
        .iter()
        .zip(&oracle)
        .enumerate()
        .filter(|(_, (a, b))| a != b)
        .map(|(i, (a, b))| format!("L{i}: mine={a:?} oracle={b:?}"))
        .collect();
    assert!(mismatches.is_empty(), "in-layer order mismatches:\n{}", mismatches.join("\n"));
}

/// E4c (stress): a 50-node flat graph with 8 backward edges
/// (`golden/stress-flat.input.json`, deterministic generator in the
/// file header of its sibling output). Exercises the subtree
/// removal/reattachment path (≥40 nodes), the pivot loop, and the
/// cycle breaker's Random tie-breaks. Uniform node sizes make the
/// oracle's y-coordinates unambiguous layer witnesses: same layer ⇔
/// same y.
#[test]
fn stress_flat_layering_matches_oracle_bands() {
    check_flat_layering_against_oracle("stress-flat");
}

/// Same check on a pure DAG (no cycle breaking involved) — isolates
/// the network simplex from Random-stream differences.
#[test]
fn dag_flat_layering_matches_oracle_bands() {
    check_flat_layering_against_oracle("dag-flat");
}

fn check_flat_layering_against_oracle(fixture: &str) {
    let read = |name: &str| {
        std::fs::read_to_string(format!(
            "{}/tools/elk-oracle/golden/{name}",
            env!("CARGO_MANIFEST_DIR")
        ))
        .unwrap()
    };
    let input: ElkNode = serde_json::from_str(&read(&format!("{fixture}.input.json"))).unwrap();
    let output: ElkNode =
        serde_json::from_str(&read(&format!("{fixture}.output.json"))).unwrap();

    // Oracle layers: rank of each distinct y.
    let mut ys: Vec<i64> = output
        .children
        .as_deref()
        .unwrap()
        .iter()
        .map(|c| c.y.unwrap().round() as i64)
        .collect();
    ys.sort_unstable();
    ys.dedup();
    let expected: std::collections::HashMap<String, usize> = output
        .children
        .as_deref()
        .unwrap()
        .iter()
        .map(|c| {
            let y = c.y.unwrap().round() as i64;
            (c.id.clone(), ys.binary_search(&y).unwrap())
        })
        .collect();

    let (arena, top) = run_through_layering(&input);
    let layers = layers_by_origin(&arena, top);
    assert_eq!(layers.len(), ys.len(), "layer count differs from oracle");
    let mut mismatches = Vec::new();
    for (li, layer) in layers.iter().enumerate() {
        for id in layer {
            if expected[id] != li {
                mismatches.push(format!("{id}: port={li} oracle={}", expected[id]));
            }
        }
    }
    assert!(mismatches.is_empty(), "layer mismatches: {mismatches:?}");
}

/// coord_diff self-check: a layout diffed against itself is clean, and
/// a perturbed copy is caught. (The tool every E4–E7 test relies on
/// must itself be trustworthy.)
#[test]
fn coord_diff_detects_perturbation() {
    let stages = stages();
    let output: ElkNode = serde_json::from_value(stages["pass2Output"].clone()).unwrap();
    assert!(coord_diff(&output, &output, 0.0).is_empty());

    let mut perturbed = output.clone();
    let child = perturbed
        .children
        .as_mut()
        .and_then(|c| c.iter_mut().next())
        .expect("root has children");
    child.x = child.x.map(|x| x + 1.0);
    let diffs = coord_diff(&output, &perturbed, 0.5);
    assert_eq!(diffs.len(), 1, "exactly the perturbed field: {diffs:?}");
    assert_eq!(diffs[0].field, "x");
}



/// E6 stage 1: the inputs the Brandes-Köpf placer consumes — node sizes
/// (transposed to the internal rightward orientation), margins, and the
/// per-side port distribution — must match elkjs exactly. The golden is
/// an instrumented elkjs dump (BK id = layer/node traversal order, which
/// matches the port since crossing-min order is byte-exact). The `y`
/// column is BK's output, verified once the placer itself is ported.
#[test]
fn bk_placement_inputs_match_oracle() {
    use typstuml::layout::elk::alg::graph::NodeType;
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (mut arena, top) = run_through_crossing_min(&input);
    typstuml::layout::elk::alg::p4nodes::prepare_placement(&mut arena, top);

    let golden = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.bk.golden"
    ))
    .unwrap();
    let mut expected: std::collections::HashMap<usize, (i32, String, String, String, String)> =
        Default::default();
    for line in golden.lines() {
        let f = |key: &str| -> String {
            line.split_whitespace()
                .find_map(|t| t.strip_prefix(key))
                .unwrap_or_default()
                .to_string()
        };
        let id: usize = f("id=").parse().unwrap();
        expected.insert(id, (f("t=").parse().unwrap(), f("sy="), f("mt="), f("mb="), f("ports=")));
    }

    let mut id = 0usize;
    let mut mismatches = Vec::new();
    for l in 0..arena.graphs[top.0].layers.len() {
        for n in arena.graphs[top.0].layers[l].nodes.clone() {
            let node = &arena.nodes[n.0];
            let t = if node.node_type == NodeType::Normal { 0 } else { 1 };
            let ports: Vec<String> = node
                .ports
                .iter()
                .map(|&p| {
                    format!(
                        "{}:{:.3}:{:.3}",
                        arena.ports[p.0].side as i32,
                        arena.ports[p.0].position.y,
                        arena.ports[p.0].anchor.y
                    )
                })
                .collect();
            let got = (
                t,
                format!("{:.3}", node.size.y),
                format!("{:.3}", node.margin.top),
                format!("{:.3}", node.margin.bottom),
                ports.join(","),
            );
            let exp = &expected[&id];
            if &got != exp {
                mismatches.push(format!("id={id}: got={got:?} exp={exp:?}"));
            }
            id += 1;
        }
    }
    assert_eq!(id, expected.len(), "node count");
    assert!(mismatches.is_empty(), "BK input mismatches:\n{}", mismatches.join("\n"));
}

/// E6: the Brandes-Köpf node placer must assign every node the same
/// in-layer coordinate as elkjs. The golden's `y` column is an
/// instrumented elkjs dump (BK id = layer/node traversal). Acceptance is
/// < 0.5pt; we get float-noise agreement.
#[test]
fn bk_node_placement_matches_oracle() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (mut arena, top) = run_through_crossing_min(&input);
    typstuml::layout::elk::alg::p4nodes::prepare_placement(&mut arena, top);
    typstuml::layout::elk::alg::p4nodes::bk::place(&mut arena, top);

    let golden = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.bk.golden"
    ))
    .unwrap();
    let mut exp: std::collections::HashMap<usize, f64> = Default::default();
    for line in golden.lines() {
        let id: usize =
            line.split_whitespace().find_map(|t| t.strip_prefix("id=")).unwrap().parse().unwrap();
        let y: f64 =
            line.split_whitespace().find_map(|t| t.strip_prefix("y=")).unwrap().parse().unwrap();
        exp.insert(id, y);
    }
    let mut id = 0usize;
    let mut max_diff = 0.0f64;
    let mut worst = String::new();
    for l in 0..arena.graphs[top.0].layers.len() {
        for n in arena.graphs[top.0].layers[l].nodes.clone() {
            let d = (arena.nodes[n.0].position.y - exp[&id]).abs();
            if d > max_diff {
                max_diff = d;
                worst = format!("id={id}: mine={} elk={}", arena.nodes[n.0].position.y, exp[&id]);
            }
            id += 1;
        }
    }
    assert_eq!(id, exp.len(), "node count");
    assert!(max_diff < 0.5, "BK y-coordinate off by {max_diff} ({worst})");
}


/// E7 (coordinate framing): given elkjs's per-gap slot counts, the
/// layer-axis x-positions the `OrthogonalEdgeRouter` assigns
/// (`placeNodesHorizontally` + layer widths + xpos accumulation) and the
/// graph width must match elkjs exactly. The slot counts themselves come
/// from the routing generator, verified separately as it is ported.
#[test]
fn edge_router_coordinate_framing_matches_oracle() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (mut arena, top) = run_through_crossing_min(&input);
    typstuml::layout::elk::alg::p4nodes::prepare_placement(&mut arena, top);
    typstuml::layout::elk::alg::p4nodes::bk::place(&mut arena, top);

    let g = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.e7.golden"
    ))
    .unwrap();
    let slots: Vec<i32> = g
        .lines()
        .filter(|l| l.starts_with("SLOTS "))
        .map(|l| l.split_whitespace().find_map(|t| t.strip_prefix("slots=")).unwrap().parse().unwrap())
        .collect();
    let mut nx: std::collections::HashMap<usize, f64> = Default::default();
    for l in g.lines().filter(|l| l.starts_with("NX ")) {
        let id: usize = l.split_whitespace().find_map(|t| t.strip_prefix("id=")).unwrap().parse().unwrap();
        let x: f64 = l.split_whitespace().find_map(|t| t.strip_prefix("x=")).unwrap().parse().unwrap();
        nx.insert(id, x);
    }
    let gx: f64 = g
        .lines()
        .find(|l| l.starts_with("GX "))
        .unwrap()
        .split_whitespace()
        .find_map(|t| t.strip_prefix("x="))
        .unwrap()
        .parse()
        .unwrap();

    let mut call = 0;
    let width = typstuml::layout::elk::alg::p5edges::route_and_place(&mut arena, top, |_a, _l, _r, _s| {
        let s = slots[call];
        call += 1;
        s
    });
    assert!((width - gx).abs() < 0.5, "graph width {width} vs {gx}");
    let mut max_diff = 0.0f64;
    for l in 0..arena.graphs[top.0].layers.len() {
        for nd in arena.graphs[top.0].layers[l].nodes.clone() {
            let id = arena.nodes[nd.0].id;
            max_diff = max_diff.max((arena.nodes[nd.0].position.x - nx[&id]).abs());
        }
    }
    assert!(max_diff < 0.5, "node x off by {max_diff}");
}


/// Full layout through phase 5, threading one JavaRandom from cycle
/// breaking through crossing-min into the orthogonal router (as ELK's
/// shared InternalProperties.RANDOM does). Flat single-component scope.
fn run_full_layout(
    input: &ElkNode,
) -> (typstuml::layout::elk::alg::graph::LGraphArena, typstuml::layout::elk::alg::graph::LGraphId) {
    use typstuml::layout::elk::alg::graph::LGraphArena;
    use typstuml::layout::elk::alg::random::JavaRandom;
    use typstuml::layout::elk::alg::{components, intermediate, p1_cycles, p2_layers, preserve_order, p4nodes};
    use typstuml::layout::elk::alg::p3order::layer_sweep;
    use typstuml::layout::elk::alg::p5edges::orthogonal;

    let mut arena = LGraphArena::default();
    let top = typstuml::layout::elk::alg::transform::import_graph(&mut arena, input);
    for comp in components::split(&mut arena, top) {
        let mut random = JavaRandom::new(1);
        p1_cycles::break_cycles(&mut arena, comp, &mut random);
        p2_layers::layer_nodes(&mut arena, comp);
        if arena.graphs[comp.0].props.high_degree_nodes_treatment {
            typstuml::layout::elk::alg::high_degree::process(&mut arena, comp);
        }
        intermediate::long_edge_splitter(&mut arena, comp);
        intermediate::port_side_processor(&mut arena, comp);
        intermediate::inverted_port_processor(&mut arena, comp);
        intermediate::port_list_sorter(&mut arena, comp);
        preserve_order::sort_by_input_model(&mut arena, comp);
        layer_sweep::layer_sweep_crossing_minimizer(&mut arena, comp, &mut random, &mut std::collections::HashMap::new());
        p4nodes::prepare_placement(&mut arena, comp);
        p4nodes::bk::place(&mut arena, comp);
        orthogonal::route_orthogonal(&mut arena, comp, &mut random);
    }
    (arena, top)
}

/// E7: the orthogonal routing generator's slot counts must reproduce
/// elkjs's — verified end-to-end through the layer x-positions (which the
/// slot counts drive) and the graph width. Correct node x + width means
/// correct per-gap slots. Bend points are checked against the oracle
/// edge sections once export lands.
#[test]
fn orthogonal_routing_slots_match_oracle() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let (arena, top) = run_full_layout(&input);

    let g = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.e7.golden"
    ))
    .unwrap();
    let mut nx: std::collections::HashMap<usize, f64> = Default::default();
    for l in g.lines().filter(|l| l.starts_with("NX ")) {
        let id: usize = l.split_whitespace().find_map(|t| t.strip_prefix("id=")).unwrap().parse().unwrap();
        let x: f64 = l.split_whitespace().find_map(|t| t.strip_prefix("x=")).unwrap().parse().unwrap();
        nx.insert(id, x);
    }
    let gx: f64 = g.lines().find(|l| l.starts_with("GX ")).unwrap()
        .split_whitespace().find_map(|t| t.strip_prefix("x=")).unwrap().parse().unwrap();

    assert!((arena.graphs[top.0].size.x - gx).abs() < 0.5, "graph width {} vs {gx}", arena.graphs[top.0].size.x);
    let mut max_diff = 0.0f64;
    let mut worst = String::new();
    for l in 0..arena.graphs[top.0].layers.len() {
        for nd in arena.graphs[top.0].layers[l].nodes.clone() {
            let id = arena.nodes[nd.0].id;
            let d = (arena.nodes[nd.0].position.x - nx[&id]).abs();
            if d > max_diff { max_diff = d; worst = format!("id={id} mine={} elk={}", arena.nodes[nd.0].position.x, nx[&id]); }
        }
    }
    assert!(max_diff < 0.5, "node x off by {max_diff} ({worst})");
}

/// E6+E7 end-to-end: after node placement + orthogonal routing, the
/// final node coordinates (internal rightward → output DOWN transpose,
/// plus graph padding) must match the elkjs oracle output within 0.5pt.
/// `output.x = internal.y − minY + pad`, `output.y = internal.x − minX +
/// pad` — a pure axis swap with a constant translation.
#[test]
fn final_node_coordinates_match_oracle() {
    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let out: ElkNode = serde_json::from_str(
        &std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tools/elk-oracle/golden/stress-flat.output.json"
        ))
        .unwrap(),
    )
    .unwrap();
    let (arena, top) = run_full_layout(&input);

    // Transpose offsets: axis minima and the graph padding.
    let mut min_y = f64::INFINITY;
    let mut min_x = f64::INFINITY;
    for l in 0..arena.graphs[top.0].layers.len() {
        for &n in &arena.graphs[top.0].layers[l].nodes {
            let node = &arena.nodes[n.0];
            min_y = min_y.min(node.position.y - node.margin.top);
            min_x = min_x.min(node.position.x - node.margin.left);
        }
    }
    let pad = arena.graphs[top.0].padding;
    let off_x = pad.left - min_y;
    let off_y = pad.top - min_x;

    let mut oracle: std::collections::HashMap<String, (f64, f64)> = Default::default();
    for c in out.children.as_deref().unwrap() {
        oracle.insert(c.id.clone(), (c.x.unwrap(), c.y.unwrap()));
    }

    let mut max_diff = 0.0f64;
    let mut worst = String::new();
    for l in 0..arena.graphs[top.0].layers.len() {
        for n in arena.graphs[top.0].layers[l].nodes.clone() {
            if let Some(origin) = arena.nodes[n.0].props.origin.clone() {
                let (ox, oy) = oracle[&origin];
                let out_x = arena.nodes[n.0].position.y + off_x;
                let out_y = arena.nodes[n.0].position.x + off_y;
                let d = (out_x - ox).abs().max((out_y - oy).abs());
                if d > max_diff {
                    max_diff = d;
                    worst = format!("{origin}: mine=({out_x:.3},{out_y:.3}) elk=({ox:.3},{oy:.3})");
                }
            }
        }
    }
    assert!(max_diff < 0.5, "node coordinate off by {max_diff} ({worst})");
}

/// E7 (waypoints): after node placement + orthogonal routing, the
/// after-phase-5 processors `LongEdgeJoiner` (reassemble the split dummy
/// chains) + `ReversedEdgeRestorer` (flip cycle-broken edges back), then
/// the export transpose, must reproduce every oracle edge section — start
/// point (source anchor), bend points, end point (target anchor) — within
/// 0.5pt. Same pure axis-swap transpose as the node coordinates.
#[test]
fn edge_waypoints_match_oracle() {
    use typstuml::layout::elk::alg::graph::LEdgeId;
    use typstuml::layout::elk::alg::intermediate;

    let raw = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/stress-flat.input.json"
    ))
    .unwrap();
    let input: ElkNode = serde_json::from_str(&raw).unwrap();
    let out: ElkNode = serde_json::from_str(
        &std::fs::read_to_string(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tools/elk-oracle/golden/stress-flat.output.json"
        ))
        .unwrap(),
    )
    .unwrap();
    let (mut arena, top) = run_full_layout(&input);

    // Export transpose offsets, from node boxes *before* joining removes
    // the long-edge dummies (identical to the node-coordinate test).
    let mut min_y = f64::INFINITY;
    let mut min_x = f64::INFINITY;
    for l in 0..arena.graphs[top.0].layers.len() {
        for &n in &arena.graphs[top.0].layers[l].nodes {
            let node = &arena.nodes[n.0];
            min_y = min_y.min(node.position.y - node.margin.top);
            min_x = min_x.min(node.position.x - node.margin.left);
        }
    }
    let pad = arena.graphs[top.0].padding;
    let off_x = pad.left - min_y;
    let off_y = pad.top - min_x;
    // Internal (ix, iy) → output DOWN: (iy + off_x, ix + off_y).
    let tp = |v: typstuml::layout::elk::alg::math::KVector| (v.y + off_x, v.x + off_y);

    intermediate::long_edge_joiner(&mut arena, top);
    intermediate::reversed_edge_restorer(&mut arena, top);

    // Oracle sections keyed by edge id.
    let oracle: std::collections::HashMap<String, &typstuml::layout::elk::graph::ElkEdgeSection> =
        out.edges.as_deref().unwrap().iter().map(|e| (e.id.clone(), &e.sections.as_ref().unwrap()[0])).collect();

    let mut checked = 0usize;
    let mut max_diff = 0.0f64;
    let mut worst = String::new();
    for e in 0..arena.edges.len() {
        let eid = LEdgeId(e);
        let (Some(src), Some(tgt)) = (arena.edges[eid.0].source, arena.edges[eid.0].target) else {
            continue; // dropped dummy edge
        };
        let Some(origin) = arena.edges[eid.0].props.origin.clone() else { continue };
        let sec = oracle.get(&origin).unwrap_or_else(|| panic!("no oracle edge {origin}"));

        let start = tp(arena.port_absolute_anchor(src));
        let end = tp(arena.port_absolute_anchor(tgt));
        let bends: Vec<(f64, f64)> =
            arena.edges[eid.0].bend_points.iter().map(|&b| tp(b)).collect();

        let mut d = (start.0 - sec.start_point.x).abs().max((start.1 - sec.start_point.y).abs());
        d = d.max((end.0 - sec.end_point.x).abs()).max((end.1 - sec.end_point.y).abs());
        let obends = sec.bend_points.clone().unwrap_or_default();
        if bends.len() != obends.len() {
            panic!("edge {origin}: {} bend points vs oracle {}", bends.len(), obends.len());
        }
        for (b, ob) in bends.iter().zip(&obends) {
            d = d.max((b.0 - ob.x).abs()).max((b.1 - ob.y).abs());
        }
        if d > max_diff {
            max_diff = d;
            worst = format!("{origin}: start mine={start:?} elk=({},{})", sec.start_point.x, sec.start_point.y);
        }
        checked += 1;
    }
    assert_eq!(checked, oracle.len(), "checked every original edge");
    assert!(max_diff < 0.5, "edge waypoint off by {max_diff} ({worst})");
}

/// E8 (hierarchy decision): `LayerSweepTypeDecider.useBottomUp()` must
/// reproduce the elkjs-instrumented map for the benchmark — root and
/// group_1 (3 real nodes) sweep bottom-up; group_2/3/4/5 are swept-into
/// (cross-hierarchy). Identifies graphs by real-node count.
#[test]
fn layer_sweep_type_decider_matches_oracle_map() {
    use typstuml::layout::elk::alg::graph::{LGraphArena, LGraphId, NodeType};
    use typstuml::layout::elk::alg::p3order::layer_sweep_type_decider::use_bottom_up;
    use typstuml::layout::elk::alg::random::JavaRandom;
    use typstuml::layout::elk::alg::{compound, high_degree, intermediate, p1_cycles, p2_layers, preserve_order, transform};

    let stages = stages_bench();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();
    let mut arena = LGraphArena::default();
    let top = transform::import_graph(&mut arena, &input);
    compound::preprocess(&mut arena, top);

    // collectAllGraphsBottomUp
    let mut graphs: Vec<LGraphId> = Vec::new();
    let mut discover = vec![top];
    while let Some(g) = discover.pop() {
        graphs.insert(0, g);
        for &n in &arena.graphs[g.0].layerless_nodes {
            if let Some(ng) = arena.nodes[n.0].nested_graph {
                discover.push(ng);
            }
        }
    }

    // Prepare every graph up to the crossing minimizer's `initialize`
    // (layered, ports sided), then assign node.id = position in layer.
    for &g in &graphs {
        let mut random = JavaRandom::new(1);
        p1_cycles::break_cycles(&mut arena, g, &mut random);
        p2_layers::layer_nodes(&mut arena, g);
        if arena.graphs[g.0].props.high_degree_nodes_treatment {
            high_degree::process(&mut arena, g);
        }
        intermediate::long_edge_splitter(&mut arena, g);
        intermediate::port_side_processor(&mut arena, g);
        intermediate::inverted_port_processor(&mut arena, g);
        intermediate::port_list_sorter(&mut arena, g);
        preserve_order::sort_by_input_model(&mut arena, g);
        for l in 0..arena.graphs[g.0].layers.len() {
            for (pos, n) in arena.graphs[g.0].layers[l].nodes.clone().into_iter().enumerate() {
                arena.nodes[n.0].id = pos;
            }
        }
    }

    for &g in &graphs {
        let real = arena.graphs[g.0]
            .layers
            .iter()
            .flat_map(|l| l.nodes.iter())
            .filter(|&&n| arena.nodes[n.0].node_type == NodeType::Normal)
            .count();
        let bu = use_bottom_up(&arena, g, false);
        // root=8 → true; group_1=3 → true; groups 2/3/4/5 (1/4/7/1) → false.
        let expected = matches!(real, 8 | 3);
        assert_eq!(bu, expected, "graph with {real} real nodes: useBottomUp={bu}, expected {expected}");
    }
}

/// E8 (nested layering): with the `FIRST_SEPARATE`/`LAST_SEPARATE`
/// external-port layer-constraint handling, every nested graph's layer
/// structure — layer count and which layer each real node lands in — must
/// match the elkjs-instrumented internal layering. (In-layer *order* is
/// the crossing-min dive, verified separately.) Hiding the external
/// dummies before layering is what makes the real-node layering agree.
#[test]
fn nested_layering_matches_oracle() {
    use typstuml::layout::elk::alg::graph::{LGraphArena, LGraphId, NodeType};
    use typstuml::layout::elk::alg::random::JavaRandom;
    use typstuml::layout::elk::alg::{
        compound, high_degree, layer_constraint, p1_cycles, p2_layers, transform,
    };

    let stages = stages_bench();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();
    let mut arena = LGraphArena::default();
    let top = transform::import_graph(&mut arena, &input);
    compound::preprocess(&mut arena, top);

    let mut graphs: Vec<LGraphId> = Vec::new();
    let mut discover = vec![top];
    while let Some(g) = discover.pop() {
        graphs.insert(0, g);
        for &n in &arena.graphs[g.0].layerless_nodes {
            if let Some(ng) = arena.nodes[n.0].nested_graph {
                discover.push(ng);
            }
        }
    }
    for &g in &graphs {
        let mut random = JavaRandom::new(1);
        p1_cycles::break_cycles(&mut arena, g, &mut random);
        let hidden = layer_constraint::preprocess(&mut arena, g);
        p2_layers::layer_nodes(&mut arena, g);
        if arena.graphs[g.0].props.high_degree_nodes_treatment {
            high_degree::process(&mut arena, g);
        }
        layer_constraint::postprocess(&mut arena, g, &hidden);
    }

    // origin → layer index, over all real nodes in every graph.
    let mut layer_of: std::collections::HashMap<String, usize> = Default::default();
    let mut layer_count: std::collections::HashMap<String, usize> = Default::default();
    for &g in &graphs {
        let gname = arena.graphs[g.0].props.origin.clone().unwrap_or_else(|| "root".into());
        layer_count.insert(gname, arena.graphs[g.0].layers.len());
        for (li, layer) in arena.graphs[g.0].layers.iter().enumerate() {
            for &n in &layer.nodes {
                if arena.nodes[n.0].node_type == NodeType::Normal {
                    if let Some(o) = arena.nodes[n.0].props.origin.clone() {
                        layer_of.insert(o, li);
                    }
                }
            }
        }
    }

    // Expected from the elkjs internal-order dump (transferNodeAndPortOrders).
    let expected_layers = [
        ("group_1", 5), ("group_2", 3), ("group_3", 4),
        ("group_4", 6), ("group_5", 3), ("root", 7),
    ];
    for (g, n) in expected_layers {
        assert_eq!(layer_count.get(g), Some(&n), "{g} layer count");
    }
    let expected_layer_of = [
        ("FE", 1), ("SV", 2), ("ED", 3),           // group_1
        ("API", 1),                                 // group_2
        ("REG", 1), ("EDIT", 1), ("GEN", 1), ("RES", 2), // group_3
        ("LAY", 1), ("TPL", 1), ("AST", 1), ("SCN", 2), ("RHTML", 3), ("RPPTX", 3), ("STO", 4), // group_4
        ("DAO", 1),                                 // group_5
        ("group_2", 0), ("group_3", 1), ("group_5", 2), ("M", 3), ("group_4", 4), ("group_1", 5), ("RC", 5), ("REST", 6), // root
    ];
    for (origin, li) in expected_layer_of {
        assert_eq!(layer_of.get(origin), Some(&li), "{origin} layer index");
    }
}

/// E8 (hierarchical crossing minimization): the full compound phase-3 run
/// on the benchmark — per-graph prep (cycle break, `*_SEPARATE` layer
/// constraints, splitter, port sides, inverted ports, port sort, model
/// order), then the hierarchy-aware `LayerSweepCrossingMinimizer` driven
/// by the root's random with per-graph child randoms — must reproduce
/// elkjs's final in-layer orders **byte-exactly** in every graph: layer
/// lengths and the exact position of every real node (which pins the
/// dummy positions too). Expected patterns are the elkjs internal-order
/// dump at `transferNodeAndPortOrdersToGraph` (`·` = dummy).
#[test]
fn nested_crossing_min_matches_oracle_order() {
    use typstuml::layout::elk::alg::graph::{LGraphArena, LGraphId};
    use typstuml::layout::elk::alg::p3order::layer_sweep;
    use typstuml::layout::elk::alg::random::JavaRandom;
    use typstuml::layout::elk::alg::{
        compound, high_degree, intermediate, layer_constraint, p1_cycles, p2_layers,
        preserve_order, transform,
    };

    let stages = stages_bench();
    let input: ElkNode = serde_json::from_value(stages["pass2Input"].clone()).unwrap();
    let mut arena = LGraphArena::default();
    let top = transform::import_graph(&mut arena, &input);
    compound::preprocess(&mut arena, top);

    // collectAllGraphsBottomUp
    let mut graphs: Vec<LGraphId> = Vec::new();
    let mut discover = vec![top];
    while let Some(g) = discover.pop() {
        graphs.insert(0, g);
        for &n in &arena.graphs[g.0].layerless_nodes {
            if let Some(ng) = arena.nodes[n.0].nested_graph {
                discover.push(ng);
            }
        }
    }

    let mut root_random = JavaRandom::new(1);
    let mut child_randoms: std::collections::HashMap<LGraphId, JavaRandom> = Default::default();
    for &g in &graphs {
        let mut random = JavaRandom::new(1);
        p1_cycles::break_cycles(&mut arena, g, &mut random);
        let hidden = layer_constraint::preprocess(&mut arena, g);
        p2_layers::layer_nodes(&mut arena, g);
        if arena.graphs[g.0].props.high_degree_nodes_treatment {
            high_degree::process(&mut arena, g);
        }
        layer_constraint::postprocess(&mut arena, g, &hidden);
        intermediate::long_edge_splitter(&mut arena, g);
        intermediate::port_side_processor(&mut arena, g);
        intermediate::inverted_port_processor(&mut arena, g);
        intermediate::port_list_sorter(&mut arena, g);
        preserve_order::sort_by_input_model(&mut arena, g);
        if g == top {
            root_random = random;
        } else {
            child_randoms.insert(g, random);
        }
    }

    layer_sweep::layer_sweep_crossing_minimizer(&mut arena, top, &mut root_random, &mut child_randoms);

    // elkjs `transferNodeAndPortOrdersToGraph` dump for the benchmark.
    let expected: &[(&str, &[&[&str]])] = &[
        ("root", &[
            &["group_2", "·"],
            &["group_3", "·"],
            &["·", "·", "group_5", "·", "·"],
            &["·", "·", "M", "·", "·"],
            &["group_4", "·"],
            &["group_1", "RC", "·"],
            &["REST"],
        ]),
        ("group_1", &[&["·"], &["·", "FE"], &["SV", "·"], &["ED", "·"], &["·"]]),
        ("group_2", &[&["·"], &["API"], &["·", "·", "·"]]),
        ("group_3", &[
            &["·", "·", "·"],
            &["REG", "·", "EDIT", "GEN"],
            &["RES", "·", "·"],
            &["·", "·", "·", "·", "·"],
        ]),
        ("group_4", &[
            &["·", "·", "·"],
            &["LAY", "TPL", "AST"],
            &["SCN"],
            &["·", "RHTML", "RPPTX"],
            &["·", "·", "STO"],
            &["·", "·"],
        ]),
        ("group_5", &[&["·", "·"], &["DAO"], &["·"]]),
    ];
    let expect_map: std::collections::HashMap<&str, &[&[&str]]> =
        expected.iter().copied().collect();

    for &g in &graphs {
        let gname = arena.graphs[g.0].props.origin.clone().unwrap_or_else(|| "root".into());
        let want = expect_map[gname.as_str()];
        assert_eq!(arena.graphs[g.0].layers.len(), want.len(), "{gname} layer count");
        for (li, layer) in arena.graphs[g.0].layers.iter().enumerate() {
            let got: Vec<String> = layer
                .nodes
                .iter()
                .map(|&n| arena.nodes[n.0].props.origin.clone().unwrap_or_else(|| "·".into()))
                .collect();
            assert_eq!(got, want[li], "{gname} L{li} in-layer order");
        }
    }
}

/// E8 (compound end-to-end): both of the benchmark's layout passes
/// through the whole compound pipeline — compound preprocessing,
/// per-graph phases, hierarchy-aware crossing minimization, per-graph
/// P4/P5 with the hierarchical port/resize processors (and, for pass 1,
/// the LEFT post-compaction), compound postprocessing, and the
/// hierarchical exporter — must reproduce elkjs's output (25 node boxes
/// across three hierarchy levels + all 20 edges' waypoints) as one
/// `coord_diff` within 0.5pt. Actual deviation is ~1e-13 (f64 noise).
/// The two passes exercise different configs: pass 1 has
/// `postCompaction=LEFT` and no `fixedAlignment` (four-sweep BK
/// everywhere); pass 2 has `fixedAlignment=BALANCED` on the root plus
/// high-degree treatment and per-group spacing overrides.
#[test]
fn compound_export_matches_oracle_output() {
    for pass in ["pass1", "pass2"] {
        check_compound_export(pass);
    }
}

fn check_compound_export(pass: &str) {
    use typstuml::layout::elk::alg::graph::LGraphArena;
    use typstuml::layout::elk::alg::{hierarchical, transform};
    use typstuml::layout::elk::compare::coord_diff;

    let stages = stages_bench();
    let input: ElkNode = serde_json::from_value(stages[format!("{pass}Input")].clone()).unwrap();
    let expected: ElkNode =
        serde_json::from_value(stages[format!("{pass}Output")].clone()).unwrap();

    let mut arena = LGraphArena::default();
    let top = transform::import_graph(&mut arena, &input);
    let result = hierarchical::layout_compound(&mut arena, top);
    let actual = transform::apply_layout_compound(&arena, top, &input, &result.reference_graphs);

    let diffs = coord_diff(&expected, &actual, 0.5);
    assert!(
        diffs.is_empty(),
        "compound export deviates from {pass}Output:\n{:#?}",
        &diffs[..diffs.len().min(20)]
    );
}

fn stages_bench() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tools/elk-oracle/golden/01-architecture.stages.json"
    );
    serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap()
}

/// E8 (flat export): the whole pipeline exported through `apply_layout`
/// (join + restore + transpose) must reproduce the entire elkjs output —
/// root box, every node box, every edge section — as one `coord_diff`
/// against the fixture's `.output.json` within 0.5pt. Covers the 50-node
/// stress graph (cycle breaking + split segments), the high-degree
/// `root-flat`, and the pure-DAG `dag-flat`.
#[test]
fn flat_export_matches_oracle_output() {
    for fixture in ["stress-flat", "root-flat", "dag-flat"] {
        check_flat_export(fixture);
    }
}

fn check_flat_export(fixture: &str) {
    use typstuml::layout::elk::alg::transform::apply_layout;
    use typstuml::layout::elk::compare::coord_diff;

    let read = |suffix: &str| {
        std::fs::read_to_string(format!(
            "{}/tools/elk-oracle/golden/{fixture}.{suffix}",
            env!("CARGO_MANIFEST_DIR")
        ))
        .unwrap()
    };
    let input: ElkNode = serde_json::from_str(&read("input.json")).unwrap();
    let expected: ElkNode = serde_json::from_str(&read("output.json")).unwrap();

    let (mut arena, top) = run_full_layout(&input);
    let actual = apply_layout(&mut arena, top);

    let diffs = coord_diff(&expected, &actual, 0.5);
    assert!(
        diffs.is_empty(),
        "{fixture}: {} geometry diffs, first 10:\n{}",
        diffs.len(),
        diffs.iter().take(10).map(|d| d.to_string()).collect::<Vec<_>>().join("\n")
    );
}


/// Adapter (draw-uml layer): the measured model — structure and order
/// from the golden `model` stage, extents from `pass1Input` (sizes are
/// inputs per the size protocol) — must reproduce both golden ELK inputs
/// byte-for-byte through `to_elk_simple` / `to_elk`, and the full
/// pipeline (`layout_model`, both engine passes + extraction +
/// post-processing) must reproduce the golden `extracted` and `final`
/// stages: every node/group box, every edge polyline (post
/// simplification), the REST icon expansion + outside-label center, and
/// the centered `__title__`.
#[test]
fn adapter_stages_match_golden() {
    use typstuml::layout::elk::adapter::{
        self, AdapterEdge, AdapterGroup, AdapterModel, AdapterNode,
    };
    use typstuml::layout::elk::compare::json_semantic_diff;

    let stages = stages_bench();
    let model_json = &stages["model"];
    let pass1_input = &stages["pass1Input"];

    // ---- measured extents, indexed from pass1Input -------------------
    #[derive(Clone)]
    struct Measured {
        width: f64,
        height: f64,
        label: Option<(String, f64, f64)>,
        padding: Option<(f64, f64, f64, f64)>,
        children: Vec<String>,
    }
    fn index_measures(node: &Value, out: &mut std::collections::HashMap<String, Measured>) {
        let children: Vec<String> = node["children"]
            .as_array()
            .map(|a| a.iter().map(|c| c["id"].as_str().unwrap().to_string()).collect())
            .unwrap_or_default();
        let label = node["labels"].as_array().and_then(|a| a.first()).map(|l| {
            (
                l["text"].as_str().unwrap_or_default().to_string(),
                l["width"].as_f64().unwrap(),
                l["height"].as_f64().unwrap(),
            )
        });
        let padding = node["layoutOptions"]["elk.padding"].as_str().map(|raw| {
            let mut p = (0.0, 0.0, 0.0, 0.0);
            for part in raw.trim_matches(['[', ']']).split(',') {
                let (k, v) = part.split_once('=').unwrap();
                let v: f64 = v.parse().unwrap();
                match k {
                    "top" => p.0 = v,
                    "left" => p.1 = v,
                    "bottom" => p.2 = v,
                    "right" => p.3 = v,
                    _ => {}
                }
            }
            p
        });
        out.insert(
            node["id"].as_str().unwrap().to_string(),
            Measured {
                width: node["width"].as_f64().unwrap_or(0.0),
                height: node["height"].as_f64().unwrap_or(0.0),
                label,
                padding,
                children,
            },
        );
        for c in node["children"].as_array().unwrap_or(&Vec::new()) {
            index_measures(c, out);
        }
    }
    let mut measures = std::collections::HashMap::new();
    index_measures(pass1_input, &mut measures);

    // ---- build the AdapterModel from `model` + measures --------------
    let mut model = AdapterModel::default();
    for n in model_json["nodes"].as_array().unwrap() {
        let id = n["id"].as_str().unwrap().to_string();
        let m = &measures[&id];
        if let Some((text, lw, lh)) = &m.label {
            // Icon node: pass1Input holds the shrunken icon box + label.
            model.nodes.push(AdapterNode {
                id,
                width: *lw,
                height: m.height + lh,
                graphic: Some((m.width, m.height)),
                node_label: Some(text.clone()),
            });
        } else {
            model.nodes.push(AdapterNode {
                id,
                width: m.width,
                height: m.height,
                graphic: None,
                node_label: None,
            });
        }
    }
    for g in model_json["groups"].as_array().unwrap() {
        let id = g["id"].as_str().unwrap().to_string();
        let m = &measures[&id];
        model.groups.push(AdapterGroup {
            id,
            children: m.children.clone(),
            padding: m.padding.expect("group must carry padding"),
        });
    }
    for e in model_json["edges"].as_array().unwrap() {
        assert!(e["label"].as_str().unwrap_or_default().is_empty());
        model.edges.push(AdapterEdge {
            id: e["id"].as_str().unwrap().to_string(),
            from: e["from"].as_str().unwrap().to_string(),
            to: e["to"].as_str().unwrap().to_string(),
            labels: Vec::new(),
            inverted: matches!(e["direction"].as_str(), Some("left") | Some("up")),
        });
    }
    let title = &stages["final"]["nodes"]["__title__"];
    model.title = Some((title["width"].as_f64().unwrap(), title["height"].as_f64().unwrap()));

    // ---- pass inputs must match the goldens ---------------------------
    let my_pass1 = serde_json::to_value(adapter::to_elk_simple(&model)).unwrap();
    let d1 = json_semantic_diff(pass1_input, &my_pass1, 1e-9);
    assert!(d1.is_empty(), "pass1Input diffs: {:#?}", &d1[..d1.len().min(15)]);

    let laid1 = adapter::run_engine(&serde_json::from_value(my_pass1).unwrap());
    let positions = adapter::collect_node_positions(&laid1);
    let my_pass2 = serde_json::to_value(adapter::to_elk(&model, &positions)).unwrap();
    let d2 = json_semantic_diff(&stages["pass2Input"], &my_pass2, 1e-9);
    assert!(d2.is_empty(), "pass2Input diffs: {:#?}", &d2[..d2.len().min(15)]);

    // ---- full pipeline vs extracted / final ----------------------------
    let layout = adapter::layout_model(&model);

    let check_against = |stage: &Value, layout: &adapter::Layout, with_title: bool| {
        let tol = 1e-6;
        let nodes = stage["nodes"].as_object().unwrap();
        for (id, n) in nodes {
            if n.is_null() {
                continue;
            }
            if id == "__title__" && !with_title {
                continue;
            }
            let mine = layout.nodes.get(id).unwrap_or_else(|| panic!("missing node {id}"));
            for (field, got) in [
                ("x", mine.x),
                ("y", mine.y),
                ("width", mine.width),
                ("height", mine.height),
            ] {
                let want = n[field].as_f64().unwrap();
                assert!((want - got).abs() < tol, "{id}.{field}: {want} != {got}");
            }
            if let Some(xl) = n.get("xlabelPos").filter(|v| !v.is_null()) {
                let got = mine.xlabel_pos.expect("expected xlabelPos");
                assert!((xl["x"].as_f64().unwrap() - got.0).abs() < tol, "{id} xlabel x");
                assert!((xl["y"].as_f64().unwrap() - got.1).abs() < tol, "{id} xlabel y");
            }
        }
        let groups = stage["groups"].as_object().unwrap();
        for (id, g) in groups {
            let mine = layout.groups.get(id).unwrap_or_else(|| panic!("missing group {id}"));
            for (field, got) in [
                ("x", mine.x),
                ("y", mine.y),
                ("width", mine.width),
                ("height", mine.height),
            ] {
                let want = g[field].as_f64().unwrap();
                assert!((want - got).abs() < tol, "group {id}.{field}: {want} != {got}");
            }
        }
        let edges = stage["edges"].as_array().unwrap();
        assert_eq!(edges.len(), layout.edges.len(), "edge count");
        for (want, got) in edges.iter().zip(&layout.edges) {
            assert_eq!(want["id"].as_str().unwrap(), got.id);
            let pts = want["points"].as_array().unwrap();
            assert_eq!(pts.len(), got.points.len(), "edge {} point count", got.id);
            for (i, (wp, gp)) in pts.iter().zip(&got.points).enumerate() {
                assert!(
                    (wp["x"].as_f64().unwrap() - gp.0).abs() < tol
                        && (wp["y"].as_f64().unwrap() - gp.1).abs() < tol,
                    "edge {} pt{i}: {wp} != {gp:?}",
                    got.id
                );
            }
        }
    };

    check_against(&stages["extracted"], &layout, false);
    check_against(&stages["final"], &layout, true);
}
